### PR TITLE
BUG(#15): Added password hash filter for user data response

### LINKED ISSUE #15: bug: API responses show user's hashed password
When returning user data, the API is showing hashed passwords like:

```JSON
{
	"id": 1,
	"username": "admin",
	"password": "8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918",
	"active": 1,
	"role": "admin",
	"created_at": "2023-11-04T14:39:45",
	"updated_at": "2023-11-04T14:39:45"
}
```

This is not secure, let's remove those from the reply's.

### PR DESCRIPTION
**Pull request by Datremar**
## What is the current behavior?

```json
{
	"id": 1,
	"username": "admin",
	"password": "8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918",
	"active": 1,
	"role": "admin",
	"created_at": "2023-11-04T14:39:45",
	"updated_at": "2023-11-04T14:39:45"
}
```

Issue Number: #15

## What is the new behavior?

- User data response doesn't contain password hash anymore:

```json
{
	"id": 1,
	"username": "admin",
	"active": 1,
	"role": "admin",
	"created_at": "2023-11-04T14:39:45",
	"updated_at": "2023-11-04T14:39:45"
}
```

## Is my code clean?

- [x] SQL lint is ok: `make sql-lint`;
- [x] Python lint is ok: `make lint`;
- [x] Test stack is ok: `docker compose up -d && make test`;

### CODE REVIEW

**Review by mariogarridopt — APPROVED** [review]

**Comment by mariogarridopt** [comment]
Hey @Datremar!
This is great, thanks for the contribution.

Please consider making this change to the other places where an auth has been passed to the result, like in:
- get_my_token
- get_my_data
- get_data
- get_users_list

I think this PR would be more complete if those were changed too.

**Comment by Datremar** [comment]
Hey @mariogarridopt!
Would you mind if I tinkered with your DAL class somewhat?
Cuz, as far as I can see, the problem with passwords takes it's root there. So I'm thinking adding some functionality to the class to be able to omit some columns.

**Comment by mariogarridopt** [comment]
> Hey @mariogarridopt! Would you mind if I tinkered with your DAL class somewhat? Cuz, as far as I can see, the problem with passwords takes it's root there. So I'm thinking adding some functionality to the class to be able to omit some columns.
> 
> Just adding excludes to every possible place for user model access isn't very viable imo

You can, but we want to be able to get passwords on code because we need to know on operations like login if the passwords match.

One thing that I thought might work was to re-write the serializable JSON method on the Auth model so that when Auth is converted to JSON the password is not passed. That way we can work with the hashed password on code, but when we convert it to JSON to send as response it removes password.

**Comment by mariogarridopt** [comment]
> The api container keeps reloading for some reason.

Make sure you run `docker compose up` from the base folder of the project.

The constant reloads are normal, the app reloads every time you change a file so that the API is already updated with the latest changes that you made to the project.

But if you get any errors on: `docker compose logs -f` paste them here or create a BUG issue so that I can look into it, just give me the most info you can regarding the problem.

**Comment by mariogarridopt** [comment]
Regarding testing your work with Postman, Insomnia or curl: be aware that some of the methods you are changing require a token on the request authentication in order for you to make the request, look at these examples: https://github.com/mariogarridopt/bookit#token

**Pull request closed without merging**
